import type { Country } from '@/services/resources/country/types.ts'
import { buildCountryTrie } from '@/services/resources/country/helpers.ts'

export const countries: Country[] = [
  { name: 'Afghanistan', isoAlpha2Code: 'AF', allowedGuesses: ['afghanistan'] },
  {
    name: 'Aland Islands',
    isoAlpha2Code: 'AX',
    allowedGuesses: ['aland islands', 'åland islands', 'aland'],
  },
  { name: 'Albania', isoAlpha2Code: 'AL', allowedGuesses: ['albania'] },
  { name: 'Algeria', isoAlpha2Code: 'DZ', allowedGuesses: ['algeria'] },
  { name: 'American Samoa', isoAlpha2Code: 'AS', allowedGuesses: ['american samoa'] },
  { name: 'Andorra', isoAlpha2Code: 'AD', allowedGuesses: ['andorra'] },
  { name: 'Angola', isoAlpha2Code: 'AO', allowedGuesses: ['angola'] },
  { name: 'Anguilla', isoAlpha2Code: 'AI', allowedGuesses: ['anguilla'] },
  { name: 'Antigua and Barbuda', isoAlpha2Code: 'AG', allowedGuesses: ['antigua and barbuda'] },
  { name: 'Argentina', isoAlpha2Code: 'AR', allowedGuesses: ['argentina'] },
  { name: 'Armenia', isoAlpha2Code: 'AM', allowedGuesses: ['armenia'] },
  { name: 'Aruba', isoAlpha2Code: 'AW', allowedGuesses: ['aruba'] },
  { name: 'Australia', isoAlpha2Code: 'AU', allowedGuesses: ['australia'] },
  { name: 'Austria', isoAlpha2Code: 'AT', allowedGuesses: ['austria'] },
  { name: 'Azerbaijan', isoAlpha2Code: 'AZ', allowedGuesses: ['azerbaijan'] },
  { name: 'Bahamas', isoAlpha2Code: 'BS', allowedGuesses: ['bahamas'] },
  { name: 'Bahrain', isoAlpha2Code: 'BH', allowedGuesses: ['bahrain'] },
  { name: 'Bangladesh', isoAlpha2Code: 'BD', allowedGuesses: ['bangladesh'] },
  { name: 'Barbados', isoAlpha2Code: 'BB', allowedGuesses: ['barbados'] },
  { name: 'Belarus', isoAlpha2Code: 'BY', allowedGuesses: ['belarus'] },
  { name: 'Belgium', isoAlpha2Code: 'BE', allowedGuesses: ['belgium'] },
  { name: 'Belize', isoAlpha2Code: 'BZ', allowedGuesses: ['belize'] },
  { name: 'Benin', isoAlpha2Code: 'BJ', allowedGuesses: ['benin'] },
  { name: 'Bermuda', isoAlpha2Code: 'BM', allowedGuesses: ['bermuda'] },
  { name: 'Bhutan', isoAlpha2Code: 'BT', allowedGuesses: ['bhutan'] },
  { name: 'Bolivia', isoAlpha2Code: 'BO', allowedGuesses: ['bolivia'] },
  {
    name: 'Bonaire, Sint Eustatius and Saba',
    isoAlpha2Code: 'BQ',
    allowedGuesses: ['bonaire', 'sint eustatius', 'saba'],
  },
  {
    name: 'Bosnia and Herzegovina',
    isoAlpha2Code: 'BA',
    allowedGuesses: ['bosnia and herzegovina'],
  },
  { name: 'Botswana', isoAlpha2Code: 'BW', allowedGuesses: ['botswana'] },
  { name: 'Brazil', isoAlpha2Code: 'BR', allowedGuesses: ['brazil'] },
  {
    name: 'British Indian Ocean Territory',
    isoAlpha2Code: 'IO',
    allowedGuesses: ['british indian ocean territory'],
  },
  {
    name: 'Brunei Darussalam',
    isoAlpha2Code: 'BN',
    allowedGuesses: ['brunei', 'brunei darussalam'],
  },
  { name: 'Bulgaria', isoAlpha2Code: 'BG', allowedGuesses: ['bulgaria'] },
  { name: 'Burkina Faso', isoAlpha2Code: 'BF', allowedGuesses: ['burkina faso'] },
  { name: 'Burundi', isoAlpha2Code: 'BI', allowedGuesses: ['burundi'] },
  { name: 'Cabo Verde', isoAlpha2Code: 'CV', allowedGuesses: ['cabo verde', 'cape verde'] },
  { name: 'Cambodia', isoAlpha2Code: 'KH', allowedGuesses: ['cambodia'] },
  { name: 'Cameroon', isoAlpha2Code: 'CM', allowedGuesses: ['cameroon'] },
  { name: 'Canada', isoAlpha2Code: 'CA', allowedGuesses: ['canada'] },
  { name: 'Cayman Islands', isoAlpha2Code: 'KY', allowedGuesses: ['cayman islands'] },
  {
    name: 'Central African Republic',
    isoAlpha2Code: 'CF',
    allowedGuesses: ['central african republic'],
  },
  { name: 'Chad', isoAlpha2Code: 'TD', allowedGuesses: ['chad'] },
  { name: 'Chile', isoAlpha2Code: 'CL', allowedGuesses: ['chile'] },
  { name: 'China', isoAlpha2Code: 'CN', allowedGuesses: ['china'] },
  { name: 'Christmas Island', isoAlpha2Code: 'CX', allowedGuesses: ['christmas island'] },
  {
    name: 'Cocos (Keeling) Islands',
    isoAlpha2Code: 'CC',
    allowedGuesses: ['cocos islands', 'keeling islands'],
  },
  { name: 'Colombia', isoAlpha2Code: 'CO', allowedGuesses: ['colombia'] },
  { name: 'Comoros', isoAlpha2Code: 'KM', allowedGuesses: ['comoros'] },
  { name: 'Congo', isoAlpha2Code: 'CG', allowedGuesses: ['congo'] },
  {
    name: 'Congo (Democratic Republic of the)',
    isoAlpha2Code: 'CD',
    allowedGuesses: ['democratic republic of the congo', 'dr congo'],
  },
  { name: 'Cook Islands', isoAlpha2Code: 'CK', allowedGuesses: ['cook islands'] },
  { name: 'Costa Rica', isoAlpha2Code: 'CR', allowedGuesses: ['costa rica'] },
  { name: 'Croatia', isoAlpha2Code: 'HR', allowedGuesses: ['croatia'] },
  { name: 'Cuba', isoAlpha2Code: 'CU', allowedGuesses: ['cuba'] },
  { name: 'Curaçao', isoAlpha2Code: 'CW', allowedGuesses: ['curaçao', 'curacao'] },
  { name: 'Cyprus', isoAlpha2Code: 'CY', allowedGuesses: ['cyprus'] },
  { name: 'Czechia', isoAlpha2Code: 'CZ', allowedGuesses: ['czechia', 'czech republic'] },
  { name: 'Denmark', isoAlpha2Code: 'DK', allowedGuesses: ['denmark'] },
  { name: 'Djibouti', isoAlpha2Code: 'DJ', allowedGuesses: ['djibouti'] },
  { name: 'Dominica', isoAlpha2Code: 'DM', allowedGuesses: ['dominica'] },
  { name: 'Dominican Republic', isoAlpha2Code: 'DO', allowedGuesses: ['dominican republic'] },
  { name: 'Ecuador', isoAlpha2Code: 'EC', allowedGuesses: ['ecuador'] },
  { name: 'Egypt', isoAlpha2Code: 'EG', allowedGuesses: ['egypt'] },
  { name: 'El Salvador', isoAlpha2Code: 'SV', allowedGuesses: ['el salvador'] },
  { name: 'Equatorial Guinea', isoAlpha2Code: 'GQ', allowedGuesses: ['equatorial guinea'] },
  { name: 'Eritrea', isoAlpha2Code: 'ER', allowedGuesses: ['eritrea'] },
  { name: 'Estonia', isoAlpha2Code: 'EE', allowedGuesses: ['estonia'] },
  { name: 'Eswatini', isoAlpha2Code: 'SZ', allowedGuesses: ['eswatini', 'swaziland'] },
  { name: 'Ethiopia', isoAlpha2Code: 'ET', allowedGuesses: ['ethiopia'] },
  {
    name: 'Falkland Islands (Malvinas)',
    isoAlpha2Code: 'FK',
    allowedGuesses: ['falkland islands', 'malvinas'],
  },
  { name: 'Faroe Islands', isoAlpha2Code: 'FO', allowedGuesses: ['faroe islands'] },
  { name: 'Fiji', isoAlpha2Code: 'FJ', allowedGuesses: ['fiji'] },
  { name: 'Finland', isoAlpha2Code: 'FI', allowedGuesses: ['finland'] },
  { name: 'France', isoAlpha2Code: 'FR', allowedGuesses: ['france'] },
  { name: 'French Guiana', isoAlpha2Code: 'GF', allowedGuesses: ['french guiana'] },
  { name: 'French Polynesia', isoAlpha2Code: 'PF', allowedGuesses: ['french polynesia'] },
  {
    name: 'French Southern Territories',
    isoAlpha2Code: 'TF',
    allowedGuesses: ['french southern territories'],
  },
  { name: 'Gabon', isoAlpha2Code: 'GA', allowedGuesses: ['gabon'] },
  { name: 'Gambia', isoAlpha2Code: 'GM', allowedGuesses: ['gambia'] },
  { name: 'Georgia', isoAlpha2Code: 'GE', allowedGuesses: ['georgia'] },
  { name: 'Germany', isoAlpha2Code: 'DE', allowedGuesses: ['germany'] },
  { name: 'Ghana', isoAlpha2Code: 'GH', allowedGuesses: ['ghana'] },
  { name: 'Gibraltar', isoAlpha2Code: 'GI', allowedGuesses: ['gibraltar'] },
  { name: 'Greece', isoAlpha2Code: 'GR', allowedGuesses: ['greece'] },
  { name: 'Greenland', isoAlpha2Code: 'GL', allowedGuesses: ['greenland'] },
  { name: 'Grenada', isoAlpha2Code: 'GD', allowedGuesses: ['grenada'] },
  { name: 'Guadeloupe', isoAlpha2Code: 'GP', allowedGuesses: ['guadeloupe'] },
  { name: 'Guam', isoAlpha2Code: 'GU', allowedGuesses: ['guam'] },
  { name: 'Guatemala', isoAlpha2Code: 'GT', allowedGuesses: ['guatemala'] },
  { name: 'Guernsey', isoAlpha2Code: 'GG', allowedGuesses: ['guernsey'] },
  { name: 'Guinea', isoAlpha2Code: 'GN', allowedGuesses: ['guinea'] },
  { name: 'Guinea-Bissau', isoAlpha2Code: 'GW', allowedGuesses: ['guinea-bissau'] },
  { name: 'Guyana', isoAlpha2Code: 'GY', allowedGuesses: ['guyana'] },
  { name: 'Haiti', isoAlpha2Code: 'HT', allowedGuesses: ['haiti'] },
  {
    name: 'Heard Island and McDonald Islands',
    isoAlpha2Code: 'HM',
    allowedGuesses: ['heard island', 'mcdonald islands'],
  },
  {
    name: 'Holy See',
    isoAlpha2Code: 'VA',
    allowedGuesses: ['holy see', 'vatican', 'vatican city'],
  },
  { name: 'Honduras', isoAlpha2Code: 'HN', allowedGuesses: ['honduras'] },
  { name: 'Hong Kong', isoAlpha2Code: 'HK', allowedGuesses: ['hong kong'] },
  { name: 'Hungary', isoAlpha2Code: 'HU', allowedGuesses: ['hungary'] },
  { name: 'Iceland', isoAlpha2Code: 'IS', allowedGuesses: ['iceland'] },
  { name: 'India', isoAlpha2Code: 'IN', allowedGuesses: ['india'] },
  { name: 'Indonesia', isoAlpha2Code: 'ID', allowedGuesses: ['indonesia'] },
  {
    name: 'Iran (Islamic Republic of)',
    isoAlpha2Code: 'IR',
    allowedGuesses: ['iran', 'iran islamic republic of'],
  },
  { name: 'Iraq', isoAlpha2Code: 'IQ', allowedGuesses: ['iraq'] },
  { name: 'Ireland', isoAlpha2Code: 'IE', allowedGuesses: ['ireland'] },
  { name: 'Isle of Man', isoAlpha2Code: 'IM', allowedGuesses: ['isle of man'] },
  { name: 'Israel', isoAlpha2Code: 'IL', allowedGuesses: ['israel'] },
  { name: 'Italy', isoAlpha2Code: 'IT', allowedGuesses: ['italy'] },
  { name: 'Jamaica', isoAlpha2Code: 'JM', allowedGuesses: ['jamaica'] },
  { name: 'Japan', isoAlpha2Code: 'JP', allowedGuesses: ['japan'] },
  { name: 'Jersey', isoAlpha2Code: 'JE', allowedGuesses: ['jersey'] },
  { name: 'Jordan', isoAlpha2Code: 'JO', allowedGuesses: ['jordan'] },
  { name: 'Kazakhstan', isoAlpha2Code: 'KZ', allowedGuesses: ['kazakhstan'] },
  { name: 'Kenya', isoAlpha2Code: 'KE', allowedGuesses: ['kenya'] },
  { name: 'Kiribati', isoAlpha2Code: 'KI', allowedGuesses: ['kiribati'] },
  {
    name: 'Korea (Democratic People’s Republic of)',
    isoAlpha2Code: 'KP',
    allowedGuesses: ['north korea', 'korea democratic people’s republic of'],
  },
  {
    name: 'Korea (Republic of)',
    isoAlpha2Code: 'KR',
    allowedGuesses: ['south korea', 'korea republic of'],
  },
  { name: 'Kuwait', isoAlpha2Code: 'KW', allowedGuesses: ['kuwait'] },
  { name: 'Kyrgyzstan', isoAlpha2Code: 'KG', allowedGuesses: ['kyrgyzstan'] },
  {
    name: 'Lao People’s Democratic Republic',
    isoAlpha2Code: 'LA',
    allowedGuesses: ['laos', 'lao people’s democratic republic'],
  },
  { name: 'Latvia', isoAlpha2Code: 'LV', allowedGuesses: ['latvia'] },
  { name: 'Lebanon', isoAlpha2Code: 'LB', allowedGuesses: ['lebanon'] },
  { name: 'Lesotho', isoAlpha2Code: 'LS', allowedGuesses: ['lesotho'] },
  { name: 'Liberia', isoAlpha2Code: 'LR', allowedGuesses: ['liberia'] },
  { name: 'Libya', isoAlpha2Code: 'LY', allowedGuesses: ['libya'] },
  { name: 'Liechtenstein', isoAlpha2Code: 'LI', allowedGuesses: ['liechtenstein'] },
  { name: 'Lithuania', isoAlpha2Code: 'LT', allowedGuesses: ['lithuania'] },
  { name: 'Luxembourg', isoAlpha2Code: 'LU', allowedGuesses: ['luxembourg'] },
  { name: 'Macao', isoAlpha2Code: 'MO', allowedGuesses: ['macao', 'macau'] },
  { name: 'Madagascar', isoAlpha2Code: 'MG', allowedGuesses: ['madagascar'] },
  { name: 'Malawi', isoAlpha2Code: 'MW', allowedGuesses: ['malawi'] },
  { name: 'Malaysia', isoAlpha2Code: 'MY', allowedGuesses: ['malaysia'] },
  { name: 'Maldives', isoAlpha2Code: 'MV', allowedGuesses: ['maldives'] },
  { name: 'Mali', isoAlpha2Code: 'ML', allowedGuesses: ['mali'] },
  { name: 'Malta', isoAlpha2Code: 'MT', allowedGuesses: ['malta'] },
  { name: 'Marshall Islands', isoAlpha2Code: 'MH', allowedGuesses: ['marshall islands'] },
  { name: 'Martinique', isoAlpha2Code: 'MQ', allowedGuesses: ['martinique'] },
  { name: 'Mauritania', isoAlpha2Code: 'MR', allowedGuesses: ['mauritania'] },
  { name: 'Mauritius', isoAlpha2Code: 'MU', allowedGuesses: ['mauritius'] },
  { name: 'Mayotte', isoAlpha2Code: 'YT', allowedGuesses: ['mayotte'] },
  { name: 'Mexico', isoAlpha2Code: 'MX', allowedGuesses: ['mexico'] },
  { name: 'Micronesia (Federated States of)', isoAlpha2Code: 'FM', allowedGuesses: ['micronesia'] },
  { name: 'Moldova (Republic of)', isoAlpha2Code: 'MD', allowedGuesses: ['moldova'] },
  { name: 'Monaco', isoAlpha2Code: 'MC', allowedGuesses: ['monaco'] },
  { name: 'Mongolia', isoAlpha2Code: 'MN', allowedGuesses: ['mongolia'] },
  { name: 'Montenegro', isoAlpha2Code: 'ME', allowedGuesses: ['montenegro'] },
  { name: 'Montserrat', isoAlpha2Code: 'MS', allowedGuesses: ['montserrat'] },
  { name: 'Morocco', isoAlpha2Code: 'MA', allowedGuesses: ['morocco'] },
  { name: 'Mozambique', isoAlpha2Code: 'MZ', allowedGuesses: ['mozambique'] },
  { name: 'Myanmar', isoAlpha2Code: 'MM', allowedGuesses: ['myanmar', 'burma'] },
  { name: 'Namibia', isoAlpha2Code: 'NA', allowedGuesses: ['namibia'] },
  { name: 'Nauru', isoAlpha2Code: 'NR', allowedGuesses: ['nauru'] },
  { name: 'Nepal', isoAlpha2Code: 'NP', allowedGuesses: ['nepal'] },
  { name: 'Netherlands', isoAlpha2Code: 'NL', allowedGuesses: ['netherlands', 'holland'] },
  { name: 'New Caledonia', isoAlpha2Code: 'NC', allowedGuesses: ['new caledonia'] },
  { name: 'New Zealand', isoAlpha2Code: 'NZ', allowedGuesses: ['new zealand'] },
  { name: 'Nicaragua', isoAlpha2Code: 'NI', allowedGuesses: ['nicaragua'] },
  { name: 'Niger', isoAlpha2Code: 'NE', allowedGuesses: ['niger'] },
  { name: 'Nigeria', isoAlpha2Code: 'NG', allowedGuesses: ['nigeria'] },
  { name: 'Niue', isoAlpha2Code: 'NU', allowedGuesses: ['niue'] },
  { name: 'Norfolk Island', isoAlpha2Code: 'NF', allowedGuesses: ['norfolk island'] },
  {
    name: 'Northern Mariana Islands',
    isoAlpha2Code: 'MP',
    allowedGuesses: ['northern mariana islands'],
  },
  { name: 'Norway', isoAlpha2Code: 'NO', allowedGuesses: ['norway'] },
  { name: 'Oman', isoAlpha2Code: 'OM', allowedGuesses: ['oman'] },
  { name: 'Pakistan', isoAlpha2Code: 'PK', allowedGuesses: ['pakistan'] },
  { name: 'Palau', isoAlpha2Code: 'PW', allowedGuesses: ['palau'] },
  {
    name: 'Palestine, State of',
    isoAlpha2Code: 'PS',
    allowedGuesses: ['palestine', 'palestine state of'],
  },
  { name: 'Panama', isoAlpha2Code: 'PA', allowedGuesses: ['panama'] },
  { name: 'Papua New Guinea', isoAlpha2Code: 'PG', allowedGuesses: ['papua new guinea'] },
  { name: 'Paraguay', isoAlpha2Code: 'PY', allowedGuesses: ['paraguay'] },
  { name: 'Peru', isoAlpha2Code: 'PE', allowedGuesses: ['peru'] },
  { name: 'Philippines', isoAlpha2Code: 'PH', allowedGuesses: ['philippines'] },
  { name: 'Pitcairn', isoAlpha2Code: 'PN', allowedGuesses: ['pitcairn'] },
  { name: 'Poland', isoAlpha2Code: 'PL', allowedGuesses: ['poland'] },
  { name: 'Portugal', isoAlpha2Code: 'PT', allowedGuesses: ['portugal'] },
  { name: 'Puerto Rico', isoAlpha2Code: 'PR', allowedGuesses: ['puerto rico'] },
  { name: 'Qatar', isoAlpha2Code: 'QA', allowedGuesses: ['qatar'] },
  { name: 'Réunion', isoAlpha2Code: 'RE', allowedGuesses: ['réunion', 'reunion'] },
  { name: 'Romania', isoAlpha2Code: 'RO', allowedGuesses: ['romania'] },
  {
    name: 'Russian Federation',
    isoAlpha2Code: 'RU',
    allowedGuesses: ['russia', 'russian federation'],
  },
  { name: 'Rwanda', isoAlpha2Code: 'RW', allowedGuesses: ['rwanda'] },
  {
    name: 'Saint Barthélemy',
    isoAlpha2Code: 'BL',
    allowedGuesses: ['saint barthélemy', 'saint barthelemy'],
  },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    isoAlpha2Code: 'SH',
    allowedGuesses: ['saint helena', 'ascension island', 'tristan da cunha'],
  },
  { name: 'Saint Kitts and Nevis', isoAlpha2Code: 'KN', allowedGuesses: ['saint kitts and nevis'] },
  { name: 'Saint Lucia', isoAlpha2Code: 'LC', allowedGuesses: ['saint lucia'] },
  {
    name: 'Saint Martin (French part)',
    isoAlpha2Code: 'MF',
    allowedGuesses: ['saint martin', 'french part'],
  },
  {
    name: 'Saint Pierre and Miquelon',
    isoAlpha2Code: 'PM',
    allowedGuesses: ['saint pierre and miquelon'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    isoAlpha2Code: 'VC',
    allowedGuesses: ['saint vincent and the grenadines'],
  },
  { name: 'Samoa', isoAlpha2Code: 'WS', allowedGuesses: ['samoa'] },
  { name: 'San Marino', isoAlpha2Code: 'SM', allowedGuesses: ['san marino'] },
  { name: 'Sao Tome and Principe', isoAlpha2Code: 'ST', allowedGuesses: ['sao tome and principe'] },
  { name: 'Saudi Arabia', isoAlpha2Code: 'SA', allowedGuesses: ['saudi arabia'] },
  { name: 'Senegal', isoAlpha2Code: 'SN', allowedGuesses: ['senegal'] },
  { name: 'Serbia', isoAlpha2Code: 'RS', allowedGuesses: ['serbia'] },
  { name: 'Seychelles', isoAlpha2Code: 'SC', allowedGuesses: ['seychelles'] },
  { name: 'Sierra Leone', isoAlpha2Code: 'SL', allowedGuesses: ['sierra leone'] },
  { name: 'Singapore', isoAlpha2Code: 'SG', allowedGuesses: ['singapore'] },
  {
    name: 'Sint Maarten (Dutch part)',
    isoAlpha2Code: 'SX',
    allowedGuesses: ['sint maarten', 'dutch part'],
  },
  { name: 'Slovakia', isoAlpha2Code: 'SK', allowedGuesses: ['slovakia'] },
  { name: 'Slovenia', isoAlpha2Code: 'SI', allowedGuesses: ['slovenia'] },
  { name: 'Solomon Islands', isoAlpha2Code: 'SB', allowedGuesses: ['solomon islands'] },
  { name: 'Somalia', isoAlpha2Code: 'SO', allowedGuesses: ['somalia'] },
  { name: 'South Africa', isoAlpha2Code: 'ZA', allowedGuesses: ['south africa'] },
  {
    name: 'South Georgia and the South Sandwich Islands',
    isoAlpha2Code: 'GS',
    allowedGuesses: ['south georgia', 'south sandwich islands'],
  },
  { name: 'South Sudan', isoAlpha2Code: 'SS', allowedGuesses: ['south sudan'] },
  { name: 'Spain', isoAlpha2Code: 'ES', allowedGuesses: ['spain'] },
  { name: 'Sri Lanka', isoAlpha2Code: 'LK', allowedGuesses: ['sri lanka'] },
  { name: 'Sudan', isoAlpha2Code: 'SD', allowedGuesses: ['sudan'] },
  { name: 'Suriname', isoAlpha2Code: 'SR', allowedGuesses: ['suriname'] },
  {
    name: 'Svalbard and Jan Mayen',
    isoAlpha2Code: 'SJ',
    allowedGuesses: ['svalbard', 'jan mayen'],
  },
  { name: 'Sweden', isoAlpha2Code: 'SE', allowedGuesses: ['sweden'] },
  { name: 'Switzerland', isoAlpha2Code: 'CH', allowedGuesses: ['switzerland'] },
  { name: 'Syrian Arab Republic', isoAlpha2Code: 'SY', allowedGuesses: ['syria'] },
  { name: 'Taiwan, Province of China', isoAlpha2Code: 'TW', allowedGuesses: ['taiwan'] },
  { name: 'Tajikistan', isoAlpha2Code: 'TJ', allowedGuesses: ['tajikistan'] },
  { name: 'Tanzania, United Republic of', isoAlpha2Code: 'TZ', allowedGuesses: ['tanzania'] },
  { name: 'Thailand', isoAlpha2Code: 'TH', allowedGuesses: ['thailand'] },
  {
    name: 'Timor-Leste',
    isoAlpha2Code: 'TL',
    allowedGuesses: ['timor-leste', 'timor leste', 'east timor'],
  },
  { name: 'Togo', isoAlpha2Code: 'TG', allowedGuesses: ['togo'] },
  { name: 'Tokelau', isoAlpha2Code: 'TK', allowedGuesses: ['tokelau'] },
  { name: 'Tonga', isoAlpha2Code: 'TO', allowedGuesses: ['tonga'] },
  { name: 'Trinidad and Tobago', isoAlpha2Code: 'TT', allowedGuesses: ['trinidad and tobago'] },
  { name: 'Tunisia', isoAlpha2Code: 'TN', allowedGuesses: ['tunisia'] },
  { name: 'Turkey', isoAlpha2Code: 'TR', allowedGuesses: ['turkey'] },
  { name: 'Turkmenistan', isoAlpha2Code: 'TM', allowedGuesses: ['turkmenistan'] },
  { name: 'Tuvalu', isoAlpha2Code: 'TV', allowedGuesses: ['tuvalu'] },
  { name: 'Uganda', isoAlpha2Code: 'UG', allowedGuesses: ['uganda'] },
  { name: 'Ukraine', isoAlpha2Code: 'UA', allowedGuesses: ['ukraine'] },
  {
    name: 'United Arab Emirates',
    isoAlpha2Code: 'AE',
    allowedGuesses: ['united arab emirates', 'uae'],
  },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    isoAlpha2Code: 'GB',
    allowedGuesses: ['united kingdom', 'uk', 'great britain'],
  },
  {
    name: 'United States of America',
    isoAlpha2Code: 'US',
    allowedGuesses: ['usa', 'us', 'united states', 'united states of america'],
  },
  { name: 'Uruguay', isoAlpha2Code: 'UY', allowedGuesses: ['uruguay'] },
  { name: 'Uzbekistan', isoAlpha2Code: 'UZ', allowedGuesses: ['uzbekistan'] },
  { name: 'Vanuatu', isoAlpha2Code: 'VU', allowedGuesses: ['vanuatu'] },
  {
    name: 'Venezuela (Bolivarian Republic of)',
    isoAlpha2Code: 'VE',
    allowedGuesses: ['venezuela'],
  },
  { name: 'Viet Nam', isoAlpha2Code: 'VN', allowedGuesses: ['vietnam', 'viet nam'] },
  { name: 'Western Sahara', isoAlpha2Code: 'EH', allowedGuesses: ['western sahara'] },
  { name: 'Yemen', isoAlpha2Code: 'YE', allowedGuesses: ['yemen'] },
  { name: 'Zambia', isoAlpha2Code: 'ZM', allowedGuesses: ['zambia'] },
  { name: 'Zimbabwe', isoAlpha2Code: 'ZW', allowedGuesses: ['zimbabwe'] },
]

console.log(countries.length)
export const trieRoot = buildCountryTrie(countries)
