import type { Country } from '@/services/resources/country/types.ts'
import { buildCountryTrie } from '@/services/resources/country/helpers.ts'

export const countries: Country[] = [
  {
    name: 'Afghanistan',
    isoAlpha2Code: 'AF',
    continents: ['asia'],
    allowedGuesses: ['afghanistan'],
  },
  { name: 'Albania', isoAlpha2Code: 'AL', continents: ['europe'], allowedGuesses: ['albania'] },
  { name: 'Algeria', isoAlpha2Code: 'DZ', continents: ['africa'], allowedGuesses: ['algeria'] },
  {
    name: 'American Samoa',
    isoAlpha2Code: 'AS',
    continents: ['oceania'],
    allowedGuesses: ['american samoa'],
  },
  { name: 'Andorra', isoAlpha2Code: 'AD', continents: ['europe'], allowedGuesses: ['andorra'] },
  { name: 'Angola', isoAlpha2Code: 'AO', continents: ['africa'], allowedGuesses: ['angola'] },
  {
    name: 'Anguilla',
    isoAlpha2Code: 'AI',
    continents: ['northAmerica'],
    allowedGuesses: ['anguilla'],
  },
  {
    name: 'Antarctica',
    isoAlpha2Code: 'AQ',
    continents: ['antarctica'],
    allowedGuesses: ['antarctica'],
  },
  {
    name: 'Antigua and Barbuda',
    isoAlpha2Code: 'AG',
    continents: ['northAmerica'],
    allowedGuesses: ['antigua and barbuda'],
  },
  {
    name: 'Argentina',
    isoAlpha2Code: 'AR',
    continents: ['southAmerica'],
    allowedGuesses: ['argentina'],
  },
  {
    name: 'Armenia',
    isoAlpha2Code: 'AM',
    continents: ['asia', 'europe'],
    allowedGuesses: ['armenia'],
  },
  {
    name: 'Australia',
    isoAlpha2Code: 'AU',
    continents: ['oceania'],
    allowedGuesses: ['australia'],
  },
  { name: 'Austria', isoAlpha2Code: 'AT', continents: ['europe'], allowedGuesses: ['austria'] },
  {
    name: 'Azerbaijan',
    isoAlpha2Code: 'AZ',
    continents: ['asia', 'europe'],
    allowedGuesses: ['azerbaijan'],
  },
  {
    name: 'Bahamas',
    isoAlpha2Code: 'BS',
    continents: ['northAmerica'],
    allowedGuesses: ['bahamas'],
  },
  { name: 'Bahrain', isoAlpha2Code: 'BH', continents: ['asia'], allowedGuesses: ['bahrain'] },
  {
    name: 'Bangladesh',
    isoAlpha2Code: 'BD',
    continents: ['asia'],
    allowedGuesses: ['bangladesh'],
  },
  {
    name: 'Barbados',
    isoAlpha2Code: 'BB',
    continents: ['northAmerica'],
    allowedGuesses: ['barbados'],
  },
  { name: 'Belarus', isoAlpha2Code: 'BY', continents: ['europe'], allowedGuesses: ['belarus'] },
  { name: 'Belgium', isoAlpha2Code: 'BE', continents: ['europe'], allowedGuesses: ['belgium'] },
  {
    name: 'Belize',
    isoAlpha2Code: 'BZ',
    continents: ['northAmerica'],
    allowedGuesses: ['belize'],
  },
  { name: 'Benin', isoAlpha2Code: 'BJ', continents: ['africa'], allowedGuesses: ['benin'] },
  {
    name: 'Bermuda',
    isoAlpha2Code: 'BM',
    continents: ['northAmerica'],
    allowedGuesses: ['bermuda'],
  },
  { name: 'Bhutan', isoAlpha2Code: 'BT', continents: ['asia'], allowedGuesses: ['bhutan'] },
  {
    name: 'Bolivia',
    isoAlpha2Code: 'BO',
    continents: ['southAmerica'],
    allowedGuesses: ['bolivia'],
  },
  {
    name: 'Bosnia and Herzegovina',
    isoAlpha2Code: 'BA',
    continents: ['europe'],
    allowedGuesses: ['bosnia and herzegovina', 'bosnia'],
  },
  { name: 'Botswana', isoAlpha2Code: 'BW', continents: ['africa'], allowedGuesses: ['botswana'] },
  {
    name: 'Brazil',
    isoAlpha2Code: 'BR',
    continents: ['southAmerica'],
    allowedGuesses: ['brazil'],
  },
  {
    name: 'British Indian Ocean Territory',
    isoAlpha2Code: 'IO',
    continents: ['asia'],
    allowedGuesses: ['british indian ocean territory'],
  },
  {
    name: 'Brunei Darussalam',
    isoAlpha2Code: 'BN',
    continents: ['asia'],
    allowedGuesses: ['brunei', 'brunei darussalam'],
  },
  { name: 'Bulgaria', isoAlpha2Code: 'BG', continents: ['europe'], allowedGuesses: ['bulgaria'] },
  {
    name: 'Burkina Faso',
    isoAlpha2Code: 'BF',
    continents: ['africa'],
    allowedGuesses: ['burkina faso'],
  },
  { name: 'Burundi', isoAlpha2Code: 'BI', continents: ['africa'], allowedGuesses: ['burundi'] },
  { name: 'Cambodia', isoAlpha2Code: 'KH', continents: ['asia'], allowedGuesses: ['cambodia'] },
  { name: 'Cameroon', isoAlpha2Code: 'CM', continents: ['africa'], allowedGuesses: ['cameroon'] },
  {
    name: 'Canada',
    isoAlpha2Code: 'CA',
    continents: ['northAmerica'],
    allowedGuesses: ['canada'],
  },
  {
    name: 'Cape Verde',
    isoAlpha2Code: 'CV',
    continents: ['africa'],
    allowedGuesses: ['cape verde'],
  },
  {
    name: 'Cayman Islands',
    isoAlpha2Code: 'KY',
    continents: ['northAmerica'],
    allowedGuesses: ['cayman islands'],
  },
  {
    name: 'Central African Republic',
    isoAlpha2Code: 'CF',
    continents: ['africa'],
    allowedGuesses: ['central african republic'],
  },
  { name: 'Chad', isoAlpha2Code: 'TD', continents: ['africa'], allowedGuesses: ['chad'] },
  { name: 'Chile', isoAlpha2Code: 'CL', continents: ['southAmerica'], allowedGuesses: ['chile'] },
  { name: 'China', isoAlpha2Code: 'CN', continents: ['asia'], allowedGuesses: ['china'] },
  {
    name: 'Colombia',
    isoAlpha2Code: 'CO',
    continents: ['southAmerica'],
    allowedGuesses: ['colombia'],
  },
  { name: 'Comoros', isoAlpha2Code: 'KM', continents: ['africa'], allowedGuesses: ['comoros'] },
  { name: 'Congo', isoAlpha2Code: 'CG', continents: ['africa'], allowedGuesses: ['congo'] },
  {
    name: 'Cook Islands',
    isoAlpha2Code: 'CK',
    continents: ['oceania'],
    allowedGuesses: ['cook islands'],
  },
  {
    name: 'Costa Rica',
    isoAlpha2Code: 'CR',
    continents: ['northAmerica'],
    allowedGuesses: ['costa rica'],
  },
  { name: 'Croatia', isoAlpha2Code: 'HR', continents: ['europe'], allowedGuesses: ['croatia'] },
  { name: 'Cuba', isoAlpha2Code: 'CU', continents: ['northAmerica'], allowedGuesses: ['cuba'] },
  {
    name: 'Curacao',
    isoAlpha2Code: 'CW',
    continents: ['northAmerica'],
    allowedGuesses: ['curacao'],
  },
  {
    name: 'Cyprus',
    isoAlpha2Code: 'CY',
    continents: ['asia', 'europe'],
    allowedGuesses: ['cyprus'],
  },
  {
    name: 'Czech Republic',
    isoAlpha2Code: 'CZ',
    continents: ['europe'],
    allowedGuesses: ['czech republic', 'czechia'],
  },
  {
    name: 'Democratic Republic of the Congo',
    isoAlpha2Code: 'CD',
    continents: ['africa'],
    allowedGuesses: ['democratic republic of the congo', 'drc'],
  },
  { name: 'Denmark', isoAlpha2Code: 'DK', continents: ['europe'], allowedGuesses: ['denmark'] },
  { name: 'Djibouti', isoAlpha2Code: 'DJ', continents: ['africa'], allowedGuesses: ['djibouti'] },
  {
    name: 'Dominica',
    isoAlpha2Code: 'DM',
    continents: ['northAmerica'],
    allowedGuesses: ['dominica'],
  },
  {
    name: 'Dominican Republic',
    isoAlpha2Code: 'DO',
    continents: ['northAmerica'],
    allowedGuesses: ['dominican republic'],
  },
  {
    name: 'Ecuador',
    isoAlpha2Code: 'EC',
    continents: ['southAmerica'],
    allowedGuesses: ['ecuador'],
  },
  {
    name: 'Egypt',
    isoAlpha2Code: 'EG',
    continents: ['africa', 'asia'],
    allowedGuesses: ['egypt'],
  },
  {
    name: 'El Salvador',
    isoAlpha2Code: 'SV',
    continents: ['northAmerica'],
    allowedGuesses: ['el salvador'],
  },
  {
    name: 'Equatorial Guinea',
    isoAlpha2Code: 'GQ',
    continents: ['africa'],
    allowedGuesses: ['equatorial guinea'],
  },
  { name: 'Eritrea', isoAlpha2Code: 'ER', continents: ['africa'], allowedGuesses: ['eritrea'] },
  { name: 'Estonia', isoAlpha2Code: 'EE', continents: ['europe'], allowedGuesses: ['estonia'] },
  {
    name: 'Eswatini',
    isoAlpha2Code: 'SZ',
    continents: ['africa'],
    allowedGuesses: ['eswatini', 'swaziland'],
  },
  { name: 'Ethiopia', isoAlpha2Code: 'ET', continents: ['africa'], allowedGuesses: ['ethiopia'] },
  {
    name: 'Falkland Islands',
    isoAlpha2Code: 'FK',
    continents: ['southAmerica'],
    allowedGuesses: ['falkland islands'],
  },
  {
    name: 'Faroe Islands',
    isoAlpha2Code: 'FO',
    continents: ['europe'],
    allowedGuesses: ['faroe islands'],
  },
  { name: 'Fiji', isoAlpha2Code: 'FJ', continents: ['oceania'], allowedGuesses: ['fiji'] },
  { name: 'Finland', isoAlpha2Code: 'FI', continents: ['europe'], allowedGuesses: ['finland'] },
  { name: 'France', isoAlpha2Code: 'FR', continents: ['europe'], allowedGuesses: ['france'] },
  {
    name: 'French Polynesia',
    isoAlpha2Code: 'PF',
    continents: ['oceania'],
    allowedGuesses: ['french polynesia'],
  },
  {
    name: 'French Southern Territories',
    isoAlpha2Code: 'TF',
    continents: ['antarctica'],
    allowedGuesses: ['french southern territories'],
  },
  { name: 'Gabon', isoAlpha2Code: 'GA', continents: ['africa'], allowedGuesses: ['gabon'] },
  { name: 'Gambia', isoAlpha2Code: 'GM', continents: ['africa'], allowedGuesses: ['gambia'] },
  {
    name: 'Georgia',
    isoAlpha2Code: 'GE',
    continents: ['asia', 'europe'],
    allowedGuesses: ['georgia'],
  },
  { name: 'Germany', isoAlpha2Code: 'DE', continents: ['europe'], allowedGuesses: ['germany'] },
  { name: 'Ghana', isoAlpha2Code: 'GH', continents: ['africa'], allowedGuesses: ['ghana'] },
  {
    name: 'Gibraltar',
    isoAlpha2Code: 'GI',
    continents: ['europe'],
    allowedGuesses: ['gibraltar'],
  },
  { name: 'Greece', isoAlpha2Code: 'GR', continents: ['europe'], allowedGuesses: ['greece'] },
  {
    name: 'Greenland',
    isoAlpha2Code: 'GL',
    continents: ['northAmerica'],
    allowedGuesses: ['greenland'],
  },
  {
    name: 'Grenada',
    isoAlpha2Code: 'GD',
    continents: ['northAmerica'],
    allowedGuesses: ['grenada'],
  },
  { name: 'Guam', isoAlpha2Code: 'GU', continents: ['oceania'], allowedGuesses: ['guam'] },
  {
    name: 'Guatemala',
    isoAlpha2Code: 'GT',
    continents: ['northAmerica'],
    allowedGuesses: ['guatemala'],
  },
  { name: 'Guernsey', isoAlpha2Code: 'GG', continents: ['europe'], allowedGuesses: ['guernsey'] },
  { name: 'Guinea', isoAlpha2Code: 'GN', continents: ['africa'], allowedGuesses: ['guinea'] },
  {
    name: 'Guinea-Bissau',
    isoAlpha2Code: 'GW',
    continents: ['africa'],
    allowedGuesses: ['guinea-bissau'],
  },
  {
    name: 'Guyana',
    isoAlpha2Code: 'GY',
    continents: ['southAmerica'],
    allowedGuesses: ['guyana'],
  },
  { name: 'Haiti', isoAlpha2Code: 'HT', continents: ['northAmerica'], allowedGuesses: ['haiti'] },
  {
    name: 'Holy See',
    isoAlpha2Code: 'VA',
    continents: ['europe'],
    allowedGuesses: ['holy see', 'vatican city'],
  },
  {
    name: 'Honduras',
    isoAlpha2Code: 'HN',
    continents: ['northAmerica'],
    allowedGuesses: ['honduras'],
  },
  { name: 'Hungary', isoAlpha2Code: 'HU', continents: ['europe'], allowedGuesses: ['hungary'] },
  { name: 'Iceland', isoAlpha2Code: 'IS', continents: ['europe'], allowedGuesses: ['iceland'] },
  { name: 'India', isoAlpha2Code: 'IN', continents: ['asia'], allowedGuesses: ['india'] },
  {
    name: 'Indonesia',
    isoAlpha2Code: 'ID',
    continents: ['asia', 'oceania'],
    allowedGuesses: ['indonesia'],
  },
  { name: 'Iran', isoAlpha2Code: 'IR', continents: ['asia'], allowedGuesses: ['iran'] },
  { name: 'Iraq', isoAlpha2Code: 'IQ', continents: ['asia'], allowedGuesses: ['iraq'] },
  { name: 'Ireland', isoAlpha2Code: 'IE', continents: ['europe'], allowedGuesses: ['ireland'] },
  {
    name: 'Isle of Man',
    isoAlpha2Code: 'IM',
    continents: ['europe'],
    allowedGuesses: ['isle of man'],
  },
  { name: 'Israel', isoAlpha2Code: 'IL', continents: ['asia'], allowedGuesses: ['israel'] },
  { name: 'Italy', isoAlpha2Code: 'IT', continents: ['europe'], allowedGuesses: ['italy'] },
  {
    name: 'Jamaica',
    isoAlpha2Code: 'JM',
    continents: ['northAmerica'],
    allowedGuesses: ['jamaica'],
  },
  { name: 'Japan', isoAlpha2Code: 'JP', continents: ['asia'], allowedGuesses: ['japan'] },
  { name: 'Jersey', isoAlpha2Code: 'JE', continents: ['europe'], allowedGuesses: ['jersey'] },
  { name: 'Jordan', isoAlpha2Code: 'JO', continents: ['asia'], allowedGuesses: ['jordan'] },
  {
    name: 'Kazakhstan',
    isoAlpha2Code: 'KZ',
    continents: ['asia', 'europe'],
    allowedGuesses: ['kazakhstan'],
  },
  { name: 'Kenya', isoAlpha2Code: 'KE', continents: ['africa'], allowedGuesses: ['kenya'] },
  {
    name: 'Kiribati',
    isoAlpha2Code: 'KI',
    continents: ['oceania'],
    allowedGuesses: ['kiribati'],
  },
  {
    name: 'Korea (North)',
    isoAlpha2Code: 'KP',
    continents: ['asia'],
    allowedGuesses: ['north korea', 'korea north', 'korea (north)'],
  },
  {
    name: 'Korea (South)',
    isoAlpha2Code: 'KR',
    continents: ['asia'],
    allowedGuesses: ['south korea', 'korea south', 'korea (south)'],
  },
  { name: 'Kuwait', isoAlpha2Code: 'KW', continents: ['asia'], allowedGuesses: ['kuwait'] },
  {
    name: 'Kyrgyzstan',
    isoAlpha2Code: 'KG',
    continents: ['asia'],
    allowedGuesses: ['kyrgyzstan'],
  },
  {
    name: 'Laos',
    isoAlpha2Code: 'LA',
    continents: ['asia'],
    allowedGuesses: ['laos', 'lao pdr'],
  },
  { name: 'Latvia', isoAlpha2Code: 'LV', continents: ['europe'], allowedGuesses: ['latvia'] },
  { name: 'Lebanon', isoAlpha2Code: 'LB', continents: ['asia'], allowedGuesses: ['lebanon'] },
  { name: 'Lesotho', isoAlpha2Code: 'LS', continents: ['africa'], allowedGuesses: ['lesotho'] },
  { name: 'Liberia', isoAlpha2Code: 'LR', continents: ['africa'], allowedGuesses: ['liberia'] },
  { name: 'Libya', isoAlpha2Code: 'LY', continents: ['africa'], allowedGuesses: ['libya'] },
  {
    name: 'Liechtenstein',
    isoAlpha2Code: 'LI',
    continents: ['europe'],
    allowedGuesses: ['liechtenstein'],
  },
  {
    name: 'Lithuania',
    isoAlpha2Code: 'LT',
    continents: ['europe'],
    allowedGuesses: ['lithuania'],
  },
  {
    name: 'Luxembourg',
    isoAlpha2Code: 'LU',
    continents: ['europe'],
    allowedGuesses: ['luxembourg'],
  },
  {
    name: 'Madagascar',
    isoAlpha2Code: 'MG',
    continents: ['africa'],
    allowedGuesses: ['madagascar'],
  },
  { name: 'Malawi', isoAlpha2Code: 'MW', continents: ['africa'], allowedGuesses: ['malawi'] },
  { name: 'Malaysia', isoAlpha2Code: 'MY', continents: ['asia'], allowedGuesses: ['malaysia'] },
  { name: 'Maldives', isoAlpha2Code: 'MV', continents: ['asia'], allowedGuesses: ['maldives'] },
  { name: 'Mali', isoAlpha2Code: 'ML', continents: ['africa'], allowedGuesses: ['mali'] },
  { name: 'Malta', isoAlpha2Code: 'MT', continents: ['europe'], allowedGuesses: ['malta'] },
  {
    name: 'Marshall Islands',
    isoAlpha2Code: 'MH',
    continents: ['oceania'],
    allowedGuesses: ['marshall islands'],
  },
  {
    name: 'Mauritania',
    isoAlpha2Code: 'MR',
    continents: ['africa'],
    allowedGuesses: ['mauritania'],
  },
  {
    name: 'Mauritius',
    isoAlpha2Code: 'MU',
    continents: ['africa'],
    allowedGuesses: ['mauritius'],
  },
  {
    name: 'Mexico',
    isoAlpha2Code: 'MX',
    continents: ['northAmerica'],
    allowedGuesses: ['mexico'],
  },
  {
    name: 'Micronesia',
    isoAlpha2Code: 'FM',
    continents: ['oceania'],
    allowedGuesses: ['micronesia'],
  },
  { name: 'Moldova', isoAlpha2Code: 'MD', continents: ['europe'], allowedGuesses: ['moldova'] },
  { name: 'Monaco', isoAlpha2Code: 'MC', continents: ['europe'], allowedGuesses: ['monaco'] },
  { name: 'Mongolia', isoAlpha2Code: 'MN', continents: ['asia'], allowedGuesses: ['mongolia'] },
  {
    name: 'Montenegro',
    isoAlpha2Code: 'ME',
    continents: ['europe'],
    allowedGuesses: ['montenegro'],
  },
  {
    name: 'Montserrat',
    isoAlpha2Code: 'MS',
    continents: ['northAmerica'],
    allowedGuesses: ['montserrat'],
  },
  { name: 'Morocco', isoAlpha2Code: 'MA', continents: ['africa'], allowedGuesses: ['morocco'] },
  {
    name: 'Mozambique',
    isoAlpha2Code: 'MZ',
    continents: ['africa'],
    allowedGuesses: ['mozambique'],
  },
  {
    name: 'Myanmar',
    isoAlpha2Code: 'MM',
    continents: ['asia'],
    allowedGuesses: ['myanmar', 'burma'],
  },
  { name: 'Namibia', isoAlpha2Code: 'NA', continents: ['africa'], allowedGuesses: ['namibia'] },
  { name: 'Nauru', isoAlpha2Code: 'NR', continents: ['oceania'], allowedGuesses: ['nauru'] },
  { name: 'Nepal', isoAlpha2Code: 'NP', continents: ['asia'], allowedGuesses: ['nepal'] },
  {
    name: 'Netherlands',
    isoAlpha2Code: 'NL',
    continents: ['europe'],
    allowedGuesses: ['netherlands'],
  },
  {
    name: 'New Caledonia',
    isoAlpha2Code: 'NC',
    continents: ['oceania'],
    allowedGuesses: ['new caledonia'],
  },
  {
    name: 'New Zealand',
    isoAlpha2Code: 'NZ',
    continents: ['oceania'],
    allowedGuesses: ['new zealand'],
  },
  {
    name: 'Nicaragua',
    isoAlpha2Code: 'NI',
    continents: ['northAmerica'],
    allowedGuesses: ['nicaragua'],
  },
  { name: 'Niger', isoAlpha2Code: 'NE', continents: ['africa'], allowedGuesses: ['niger'] },
  { name: 'Nigeria', isoAlpha2Code: 'NG', continents: ['africa'], allowedGuesses: ['nigeria'] },
  { name: 'Niue', isoAlpha2Code: 'NU', continents: ['oceania'], allowedGuesses: ['niue'] },
  {
    name: 'North Macedonia',
    isoAlpha2Code: 'MK',
    continents: ['europe'],
    allowedGuesses: ['north macedonia'],
  },
  {
    name: 'Northern Mariana Islands',
    isoAlpha2Code: 'MP',
    continents: ['oceania'],
    allowedGuesses: ['northern mariana islands'],
  },
  { name: 'Norway', isoAlpha2Code: 'NO', continents: ['europe'], allowedGuesses: ['norway'] },
  { name: 'Oman', isoAlpha2Code: 'OM', continents: ['asia'], allowedGuesses: ['oman'] },
  { name: 'Pakistan', isoAlpha2Code: 'PK', continents: ['asia'], allowedGuesses: ['pakistan'] },
  { name: 'Palau', isoAlpha2Code: 'PW', continents: ['oceania'], allowedGuesses: ['palau'] },
  { name: 'Palestine', isoAlpha2Code: 'PS', continents: ['asia'], allowedGuesses: ['palestine'] },
  {
    name: 'Panama',
    isoAlpha2Code: 'PA',
    continents: ['northAmerica'],
    allowedGuesses: ['panama'],
  },
  {
    name: 'Papua New Guinea',
    isoAlpha2Code: 'PG',
    continents: ['oceania'],
    allowedGuesses: ['papua new guinea'],
  },
  {
    name: 'Paraguay',
    isoAlpha2Code: 'PY',
    continents: ['southAmerica'],
    allowedGuesses: ['paraguay'],
  },
  { name: 'Peru', isoAlpha2Code: 'PE', continents: ['southAmerica'], allowedGuesses: ['peru'] },
  {
    name: 'Philippines',
    isoAlpha2Code: 'PH',
    continents: ['asia'],
    allowedGuesses: ['philippines'],
  },
  {
    name: 'Pitcairn',
    isoAlpha2Code: 'PN',
    continents: ['oceania'],
    allowedGuesses: ['pitcairn'],
  },
  { name: 'Poland', isoAlpha2Code: 'PL', continents: ['europe'], allowedGuesses: ['poland'] },
  { name: 'Portugal', isoAlpha2Code: 'PT', continents: ['europe'], allowedGuesses: ['portugal'] },
  {
    name: 'Puerto Rico',
    isoAlpha2Code: 'PR',
    continents: ['northAmerica'],
    allowedGuesses: ['puerto rico'],
  },
  { name: 'Qatar', isoAlpha2Code: 'QA', continents: ['asia'], allowedGuesses: ['qatar'] },
  { name: 'Romania', isoAlpha2Code: 'RO', continents: ['europe'], allowedGuesses: ['romania'] },
  {
    name: 'Russia',
    isoAlpha2Code: 'RU',
    continents: ['europe', 'asia'],
    allowedGuesses: ['russia'],
  },
  { name: 'Rwanda', isoAlpha2Code: 'RW', continents: ['africa'], allowedGuesses: ['rwanda'] },
  {
    name: 'Saint Barthelemy',
    isoAlpha2Code: 'BL',
    continents: ['northAmerica'],
    allowedGuesses: ['saint barthelemy'],
  },
  {
    name: 'Saint Helena',
    isoAlpha2Code: 'SH',
    continents: ['africa'],
    allowedGuesses: ['saint helena'],
  },
  {
    name: 'Saint Kitts and Nevis',
    isoAlpha2Code: 'KN',
    continents: ['northAmerica'],
    allowedGuesses: ['saint kitts and nevis'],
  },
  {
    name: 'Saint Lucia',
    isoAlpha2Code: 'LC',
    continents: ['northAmerica'],
    allowedGuesses: ['saint lucia'],
  },
  {
    name: 'Saint Martin',
    isoAlpha2Code: 'MF',
    continents: ['northAmerica'],
    allowedGuesses: ['saint martin'],
  },
  {
    name: 'Saint Pierre and Miquelon',
    isoAlpha2Code: 'PM',
    continents: ['northAmerica'],
    allowedGuesses: ['saint pierre and miquelon'],
  },
  {
    name: 'Saint Vincent and the Grenadines',
    isoAlpha2Code: 'VC',
    continents: ['northAmerica'],
    allowedGuesses: ['saint vincent and the grenadines'],
  },
  { name: 'Samoa', isoAlpha2Code: 'WS', continents: ['oceania'], allowedGuesses: ['samoa'] },
  {
    name: 'San Marino',
    isoAlpha2Code: 'SM',
    continents: ['europe'],
    allowedGuesses: ['san marino'],
  },
  {
    name: 'Sao Tome and Principe',
    isoAlpha2Code: 'ST',
    continents: ['africa'],
    allowedGuesses: ['sao tome and principe'],
  },
  {
    name: 'Saudi Arabia',
    isoAlpha2Code: 'SA',
    continents: ['asia'],
    allowedGuesses: ['saudi arabia'],
  },
  { name: 'Senegal', isoAlpha2Code: 'SN', continents: ['africa'], allowedGuesses: ['senegal'] },
  { name: 'Serbia', isoAlpha2Code: 'RS', continents: ['europe'], allowedGuesses: ['serbia'] },
  {
    name: 'Seychelles',
    isoAlpha2Code: 'SC',
    continents: ['africa'],
    allowedGuesses: ['seychelles'],
  },
  {
    name: 'Sierra Leone',
    isoAlpha2Code: 'SL',
    continents: ['africa'],
    allowedGuesses: ['sierra leone'],
  },
  { name: 'Singapore', isoAlpha2Code: 'SG', continents: ['asia'], allowedGuesses: ['singapore'] },
  {
    name: 'Sint Maarten',
    isoAlpha2Code: 'SX',
    continents: ['northAmerica'],
    allowedGuesses: ['sint maarten'],
  },
  { name: 'Slovakia', isoAlpha2Code: 'SK', continents: ['europe'], allowedGuesses: ['slovakia'] },
  { name: 'Slovenia', isoAlpha2Code: 'SI', continents: ['europe'], allowedGuesses: ['slovenia'] },
  {
    name: 'Solomon Islands',
    isoAlpha2Code: 'SB',
    continents: ['oceania'],
    allowedGuesses: ['solomon islands'],
  },
  { name: 'Somalia', isoAlpha2Code: 'SO', continents: ['africa'], allowedGuesses: ['somalia'] },
  {
    name: 'South Africa',
    isoAlpha2Code: 'ZA',
    continents: ['africa'],
    allowedGuesses: ['south africa'],
  },
  {
    name: 'South Georgia and the South Sandwich Islands',
    isoAlpha2Code: 'GS',
    continents: ['antarctica'],
    allowedGuesses: ['south georgia and the south sandwich islands'],
  },
  {
    name: 'South Sudan',
    isoAlpha2Code: 'SS',
    continents: ['africa'],
    allowedGuesses: ['south sudan'],
  },
  { name: 'Spain', isoAlpha2Code: 'ES', continents: ['europe'], allowedGuesses: ['spain'] },
  { name: 'Sri Lanka', isoAlpha2Code: 'LK', continents: ['asia'], allowedGuesses: ['sri lanka'] },
  { name: 'Sudan', isoAlpha2Code: 'SD', continents: ['africa'], allowedGuesses: ['sudan'] },
  {
    name: 'Suriname',
    isoAlpha2Code: 'SR',
    continents: ['southAmerica'],
    allowedGuesses: ['suriname'],
  },
  { name: 'Sweden', isoAlpha2Code: 'SE', continents: ['europe'], allowedGuesses: ['sweden'] },
  {
    name: 'Switzerland',
    isoAlpha2Code: 'CH',
    continents: ['europe'],
    allowedGuesses: ['switzerland'],
  },
  {
    name: 'Syrian Arab Republic',
    isoAlpha2Code: 'SY',
    continents: ['asia'],
    allowedGuesses: ['syria', 'syrian arab republic'],
  },
  // { name: 'Taiwan', isoAlpha2Code: 'TW', continents: ['asia'], allowedGuesses: ['taiwan'] },
  {
    name: 'Tajikistan',
    isoAlpha2Code: 'TJ',
    continents: ['asia'],
    allowedGuesses: ['tajikistan'],
  },
  { name: 'Tanzania', isoAlpha2Code: 'TZ', continents: ['africa'], allowedGuesses: ['tanzania'] },
  { name: 'Thailand', isoAlpha2Code: 'TH', continents: ['asia'], allowedGuesses: ['thailand'] },
  {
    name: 'Timor-Leste',
    isoAlpha2Code: 'TL',
    continents: ['asia'],
    allowedGuesses: ['timor-leste', 'east timor'],
  },
  { name: 'Togo', isoAlpha2Code: 'TG', continents: ['africa'], allowedGuesses: ['togo'] },
  { name: 'Tokelau', isoAlpha2Code: 'TK', continents: ['oceania'], allowedGuesses: ['tokelau'] },
  { name: 'Tonga', isoAlpha2Code: 'TO', continents: ['oceania'], allowedGuesses: ['tonga'] },
  {
    name: 'Trinidad and Tobago',
    isoAlpha2Code: 'TT',
    continents: ['northAmerica'],
    allowedGuesses: ['trinidad and tobago'],
  },
  { name: 'Tunisia', isoAlpha2Code: 'TN', continents: ['africa'], allowedGuesses: ['tunisia'] },
  {
    name: 'Turkey',
    isoAlpha2Code: 'TR',
    continents: ['asia', 'europe'],
    allowedGuesses: ['turkey'],
  },
  {
    name: 'Turkmenistan',
    isoAlpha2Code: 'TM',
    continents: ['asia'],
    allowedGuesses: ['turkmenistan'],
  },
  { name: 'Tuvalu', isoAlpha2Code: 'TV', continents: ['oceania'], allowedGuesses: ['tuvalu'] },
  { name: 'Uganda', isoAlpha2Code: 'UG', continents: ['africa'], allowedGuesses: ['uganda'] },
  { name: 'Ukraine', isoAlpha2Code: 'UA', continents: ['europe'], allowedGuesses: ['ukraine'] },
  {
    name: 'United Arab Emirates',
    isoAlpha2Code: 'AE',
    continents: ['asia'],
    allowedGuesses: ['united arab emirates', 'uae'],
  },
  {
    name: 'United Kingdom',
    isoAlpha2Code: 'GB',
    continents: ['europe'],
    allowedGuesses: ['united kingdom', 'uk', 'great britain'],
  },
  {
    name: 'United States',
    isoAlpha2Code: 'US',
    continents: ['northAmerica'],
    allowedGuesses: ['united states', 'usa', 'us'],
  },
  {
    name: 'Uruguay',
    isoAlpha2Code: 'UY',
    continents: ['southAmerica'],
    allowedGuesses: ['uruguay'],
  },
  {
    name: 'Uzbekistan',
    isoAlpha2Code: 'UZ',
    continents: ['asia'],
    allowedGuesses: ['uzbekistan'],
  },
  { name: 'Vanuatu', isoAlpha2Code: 'VU', continents: ['oceania'], allowedGuesses: ['vanuatu'] },
  {
    name: 'Venezuela',
    isoAlpha2Code: 'VE',
    continents: ['southAmerica'],
    allowedGuesses: ['venezuela'],
  },
  { name: 'Vietnam', isoAlpha2Code: 'VN', continents: ['asia'], allowedGuesses: ['vietnam'] },
  { name: 'Yemen', isoAlpha2Code: 'YE', continents: ['asia'], allowedGuesses: ['yemen'] },
  { name: 'Zambia', isoAlpha2Code: 'ZM', continents: ['africa'], allowedGuesses: ['zambia'] },
  { name: 'Zimbabwe', isoAlpha2Code: 'ZW', continents: ['africa'], allowedGuesses: ['zimbabwe'] },
]

export const trieRoot = buildCountryTrie(countries)
